#include <stdlib.h>
#include <stdio.h>
#include <string>
#include <sys/stat.h>
#include "SpiceUsr.h"

using namespace std;

void getTargetState(double et, const char* spacecraft, const char* observerBody, const char* targetBody, double targetpos[3], double velocity[3]);
void getSpacecraftState(double et, const char* spacecraft, const char* observerBody, double scPosition[3], double velocity[3]);

/*
  This program writes a file containing the apparent (light-time corrected) positions of the
  spacecraft, Sun, and Earth relative to the body, in the body-fixed coordinate system. Time
  sampling is determined based on the body rotation rate, if input, otherwise a default time
  sampling is used.
 */
int main(int nargs, char** argv)
{
	#define SECPERMIN 60
	#define MINPERHR  60
	#define HRPERDAY  24
	#define DEGPERREV 360

	SpiceDouble et;
	SpiceDouble startEt;
	SpiceDouble endEt;

    char utc[25];
    SpiceDouble scposb[3];
    SpiceDouble scvelb[3];
    SpiceDouble sunpos[3];
    SpiceDouble unused[3];
    SpiceDouble earthpos[3];
    SpiceDouble stepSize;
    SpiceDouble spinRate;
    FILE *fp;

	if (nargs < 6)
	{
	    fprintf(stderr, "\nThis program outputs a time history of the spacecraft, Sun, and Earth positions.\n");
	    fprintf(stderr, "Time sampling step size is determined based on the optional parameter spinRate.\n");
	    fprintf(stderr, "If not provided, a default time sampling step size of 10 minutes is used.\n");
	    fprintf(stderr, "usage: timeHistory <body> <spacecraft> <metaKernel> <startTime> <endTime> <spinRate>\n");
	    fprintf(stderr, "       body                  - IAU name of body in uppercase\n");
	    fprintf(stderr, "       spacecraft            - SPICE name of spacecraft\n");
	    fprintf(stderr, "       metaKernel            - file name of SPICE metakernel,\n");
	    fprintf(stderr, "                               which must include (at least) the following kernels:\n");
	    fprintf(stderr, "                               planetary SPK, target SPK, target body-fixed PCK,\n");
	    fprintf(stderr, "                               spacecraft SPK, and leap seconds LSK\n");
	    fprintf(stderr, "       startEt               - SPICE string representation of start time of history\n");
	    fprintf(stderr, "       startEt               - SPICE string representation of end time of history\n");
	    fprintf(stderr, "       spinRate (optional)   - body rotation period in days per revolution\n");
	    fprintf(stderr, "example:\n");
	    fprintf(stderr, "       timeHistory EROS NEAR kernelsEros.tm \"2000-105::05:12:04.273 UTC\" \"2000-105::20:00:00 UTC\" .2194\n");
	    fprintf(stderr, "output file: <SC>_<BODY>_timeHistory.csv\n\n");
	    exit(1);
	}
	if (nargs < 7)
	{
		/*--------------------------------------*/
		/* Default to 10 minutes step size.     */
		/*--------------------------------------*/

	    stepSize = 10 * SECPERMIN;
	}
	if (nargs == 7)
	{
		/*--------------------------------------*/
		/* Calculate step size such that there  */
		/* is a time sample each 10 degrees of  */
		/* body rotation.                       */
		/*--------------------------------------*/

		spinRate = atof(argv[6]) * SECPERMIN * MINPERHR * HRPERDAY;
	    stepSize = 10 * spinRate / DEGPERREV;
	}

	printf("\nTime sampling step size: %f sec.\n", stepSize);

	const char* body = argv[1];
    const char* sc = argv[2];
    const char* metakernel = argv[3];
    const char* defaultStart = argv[4];
    const char* defaultEnd = argv[5];

	/*--------------------------------------*/
	/* Load kernels                         */
	/*--------------------------------------*/

	furnsh_c(metakernel);

	/*--------------------------------------*/
	/* Get Ephemeris time                   */
	/*--------------------------------------*/

	str2et_c (defaultStart , &startEt );
	str2et_c (defaultEnd , &endEt );

	/*--------------------------------------*/
	/* Prepare output file.                 */
	/*--------------------------------------*/

	string fname = sc + string("_") + body + string("_timeHistory.csv");

    if((fp = fopen(fname.c_str(), "wb"))==NULL)
    {
        printf("Cannot open output file.\n");
        return 1;
    }

	/*--------------------------------------*/
	/* For each time step dump time history */
	/*--------------------------------------*/

    fprintf(fp, "#UTC, Sun x, Sun y, Sun z, Earth x, Earth y, Earth z, SC x, SC y, SC z, SCV x, SCV y, SCV z\n");

	et = startEt;
	while (et < endEt)
	{
		/*--------------------------------------*/
		/* These don't handle light time        */
		/* correctly. Note that Eros infofiles  */
		/* generated by Eli have values that    */
		/* match the output of these functions. */
		/* They use the following call:         */
		/* spkpos(target, et, ref, abcorr, obs, */
		/* pos, &lt), where in all cases, the   */
		/* target is the body whose position is */
		/* desired (e.g. the spacecraft, Sun,   */
		/* or Earth), the observer is the small */
		/* body, et is the image time, and      */
		/* abcorr is "LT+S".                    */
		/*--------------------------------------*/

//		getScPosition(et, scposb);
//		getSunPosition(et, sunpos);
//		getEarthPosition(et, earthpos);

		/*--------------------------------------*/
		/* The light time calcuation derived by */
		/* Howard Taylor for SBMT NH LORRI data */
		/* works only for the spacecraft        */
		/* position. Corrected functions for    */
		/* non-spacecraft bodies are below.     */
		/*--------------------------------------*/

		getSpacecraftState(et, sc, body, scposb, scvelb);
		getTargetState(et, sc, body, "SUN", sunpos, unused);
		getTargetState(et, sc, body, "EARTH", earthpos, unused);
		
		/*--------------------------------------*/
		/* Both of these calculations correctly */
		/* convert et to utc. The former outputs*/
		/* time in YYY-MM-DD format, the latter */
		/* in day of year format.               */
		/*--------------------------------------*/

	    et2utc_c(et, "ISOC", 3, 25, utc);
//		timout_c ( et, "YYYY-DOYTHR:MN:SC.### ::UTC", 32, utc );

		fprintf(fp, "%s, %2.8e, %2.8e, %2.8e, %2.8e, %2.8e, %2.8e, %2.8e, %2.8e, %2.8e , %2.8e, %2.8e, %2.8e \n", utc, sunpos[0], sunpos[1], sunpos[2], earthpos[0], earthpos[1], earthpos[2], scposb[0], scposb[1], scposb[2], scvelb[0], scvelb[1], scvelb[2]);

		et = et + stepSize;
	}

    fclose(fp);
	printf("Output written to: %s\n\n", fname.c_str());
	return 0;
}
