#include <stdlib.h>
#include <stdio.h>
#include <string>
#include <sys/stat.h>
#include "SpiceUsr.h"

using namespace std;

//void getScPosition(double et, double scposb[3]);
//void getSunPosition(double et, double sunpos[3]);
//void getEarthPosition(double et, double earthpos[3]);
void getTargetBodyPosition(double et, const char* observerBody, const char* targetBody, double targetpos[3]);

/*
  This program writes a file containing the apparent (light-time corrected) positions of the
  spacecraft, Sun, and Earth relative to the body, in the body-fixed coordinate system. Time
  sampling is determined based on the body rotation rate, if input, otherwise a default time
  sampling is used.
 */
int main(int nargs, char** argv)
{
	#define SECPERMIN 60
	#define MINPERHR  60
	#define HRPERDAY  24
	#define DEGPERREV 360

	SpiceDouble et;
	SpiceDouble startEt;
	SpiceDouble endEt;

    char utc[25];
    SpiceDouble scposb[3];
    SpiceDouble sunpos[3];
    SpiceDouble earthpos[3];
    SpiceDouble stepSize;
    SpiceDouble spinRate;
    FILE *fp;

	if (nargs < 6)
	{
	    fprintf(stderr, "\nThis program outputs a time history of the spacecraft, Sun, and Earth positions.\n");
	    fprintf(stderr, "\nTime sampling step size is determined based on the optional parameter spinRate.\n");
	    fprintf(stderr, "\nIf not provided, a default time sampling step size of 10 minutes is used.\n");
	    fprintf(stderr, "usage: timeHistory <body> <spacecraft> <metaKernel> <startTime> <endTime> <spinRate>\n");
	    fprintf(stderr, "       body                  - IAU name of body in uppercase\n");
	    fprintf(stderr, "       spacecraft            - SPICE name of spacecraft\n");
	    fprintf(stderr, "       metaKernel            - file name of SPICE metakernel\n");
	    fprintf(stderr, "       startEt               - SPICE string representation of start time of history\n");
	    fprintf(stderr, "       startEt               - SPICE string representation of end time of history\n");
	    fprintf(stderr, "       spinRate (optional)   - body rotation period in days per revolution\n");
	    fprintf(stderr, "example:\n");
	    fprintf(stderr, "       timeHistory EROS NEAR kernelsEros.tm \"2000-105::05:12:04.273 UTC\" \"2000-105::06:00:00 UTC\" 60\n\n");
	    exit(1);
	}
	if (nargs < 7)
	{
		/*--------------------------------------*/
		/* Default to 10 minutes step size.     */
		/*--------------------------------------*/

	    stepSize = 10 * SECPERMIN;
	}
	if (nargs == 7)
	{
		/*--------------------------------------*/
		/* Calculate step size such that there  */
		/* is a time sample each 10 degrees of  */
		/* body rotation.                       */
		/*--------------------------------------*/

		spinRate = atof(argv[6]) * SECPERMIN * MINPERHR * HRPERDAY;
	    stepSize = 10 * spinRate / DEGPERREV;
	}

	printf("\nTime sampling step size: %f sec.\n", stepSize);

	const char* body = argv[1];
    const char* sc = argv[2];
    const char* metakernel = argv[3];
    const char* defaultStart = argv[4];
    const char* defaultEnd = argv[5];

	/*--------------------------------------*/
	/* Load kernels                         */
	/*--------------------------------------*/

	furnsh_c(metakernel);

	/*--------------------------------------*/
	/* Get Ephemeris time                   */
	/*--------------------------------------*/

	str2et_c (defaultStart , &startEt );
	str2et_c (defaultEnd , &endEt );

	/*--------------------------------------*/
	/* Prepare output file.                 */
	/*--------------------------------------*/

	string fname = sc + string("_") + body + string("_timeHistory.txt");

    if((fp = fopen(fname.c_str(), "wb"))==NULL)
    {
        printf("Cannot open output file.\n");
        return 1;
    }

	/*--------------------------------------*/
	/* For each time step dump time history */
	/*--------------------------------------*/

    fprintf(fp, "#UTC, Sun x, Sun y, Sun z, Earth x, Earth y, Earth z, SC x, SC y, SC z\n");

	et = startEt;
	while (et < endEt)
	{
		/*--------------------------------------*/
		/* These don't handle light time        */
		/* correctly. Note that Eros infofiles  */
		/* generated by Eli have values that    */
		/* match the output of these functions. */
		/*--------------------------------------*/

//		getScPosition(et, scposb);
//		getSunPosition(et, sunpos);
//		getEarthPosition(et, earthpos);

		/*--------------------------------------*/
		/* getTargetBodyPosition uses the light */
		/* time calcuation derived by Howard    */
		/* Taylor for SBMT NH LORRI data.       */
		/*--------------------------------------*/

		getTargetBodyPosition(et, body, sc, scposb);
		getTargetBodyPosition(et, body, "SUN", sunpos);
		getTargetBodyPosition(et, body, "EARTH", earthpos);
		
		/*--------------------------------------*/
		/* Both of these calculations correctly */
		/* convert et to utc. The former outputs*/
		/* time in YYY-MM-DD format.            */
		/*--------------------------------------*/

//	    et2utc_c(et, "ISOC", 3, 25, utc);
		timout_c ( et, "YYYY-DOYTHR:MN:SC.### ::UTC", 32, utc );

		fprintf(fp, "%s, %2.10e, %2.10e, %2.10e, %2.10e, %2.10e, %2.10e, %2.7e, %2.7e, %2.7e \n", utc, sunpos[0], sunpos[1], sunpos[2], earthpos[0], earthpos[1], earthpos[2], scposb[0], scposb[1], scposb[2]);

		et = et + stepSize;
	}

    fclose(fp);
	printf("Output written to %s\n\n", fname.c_str());
	return 0;
}
