package edu.jhuapl.near.model;

public enum ModelNames
{
    SMALL_BODY,
    LINE_STRUCTURES,
    POLYGON_STRUCTURES,
    CIRCLE_STRUCTURES,
    ELLIPSE_STRUCTURES,
    POINT_STRUCTURES,
    CIRCLE_SELECTION,
    IMAGES,
    GRATICULE,
    GRAVITY_VECTOR_FIELD,
    COLOR_IMAGES,
    PERSPECTIVE_IMAGE_BOUNDARIES,
    LINEAMENT,
    SPECTRA,
    LIDAR_SUMMARY,
    LIDAR_BROWSE,
    LIDAR_SEARCH,
    MAPLET_BOUNDARY
}
