#!/usr/bin/env python

# There is a nightly cron job that generates a New Horizons metakernel
# file every day at /project/lorri/kernels/nh_auto.mk. Unfortunately,
# the metakernel is missing a few kernels we need. This program
# therefore generates a new metakernel file with the new kernels
# appended to the end of the original metakernel and saves the new
# kernel to the current folder in a file called nh_spice.mk.

import glob

# Read in original SPICE metakernel file which is autogenerated nightly
orig_spice_file = open ("/project/lorri/kernels/nh_auto.mk", "r")
orig_spice=orig_spice_file.read()


navpefiles = sorted(glob.glob("/project/lorri/kernels/spk/NavPE_de433_od*.bsp"))
navsefiles = sorted(glob.glob("/project/lorri/kernels/spk/NavSE_plu043_od*.bsp"))

print "NavPE:"
print navpefiles
print "NavSE:"
print navsefiles

# Add 2 more kernels to the original meta kernel since for some
# reason, they are not included in the original meta kernel file
fout = open('nh_spice.mk', 'w')
fout.write(orig_spice)
fout.write("\\begindata\n")
fout.write("KERNELS_TO_LOAD += ('" + navpefiles[-1] + "'\n")
fout.write("                    '" + navsefiles[-1] + "'\n")
fout.write("                    )\n")
fout.write("\\begintext\n")
fout.close()
