#!/bin/bash

# This script is meant to be run as a daily cron job. It checks to see
# if there are any new New Horizons images and makes them available to
# the SBMT. It must be run the machine called kuiper.

set -e
set -o pipefail
export JAVA_HOME=/project/nearsdc/software/java/x86_64/jdk1.6.0_35
export PATH=${JAVA_HOME}/bin:${PATH}
export PATH=/project/nearsdc/software/apache-ant/latest/bin:${PATH}

DIR=/project/nearsdc/nh-sbmt
cd $DIR

# Create an updated SPICE metakernel file with more kernels than the
# one generated by Howie Taylor
./createUpdatedSpiceMetaKernel.py

# run git clone on kenny since that machine has a decent version of git
rm -rf $DIR/sbmt
ssh kenny "cd $DIR; git clone http://hardin:8080/scm/git/sbmt"

# Compile SBMT
cd $DIR/sbmt
./config/build-sbmt-extras.sh

# Copy over any new LORRI fits data
mkdir -p /project/nearsdc/data/NEWHORIZONS/LORRI/images2
find /project/lorri/data/soc/pluto/level2/lor/current -name "*fit" | xargs cp -R -u -L -t /project/nearsdc/data/NEWHORIZONS/LORRI/images2
# remove the 4x4 and other non-useful images
rm -f /project/nearsdc/data/NEWHORIZONS/LORRI/images2/*_0x63{3,4,5,9,A,B}*.fit

# copy over Simon Porter's WCS-corrected FITS files
find /project/lorri/data/soc/porter/pwcs1 -name "*fits" | xargs cp -R -u -L -t /project/nearsdc/data/NEWHORIZONS/LORRI/images2
for i in /project/nearsdc/data/NEWHORIZONS/LORRI/images2/*pwcs1.fits
do
   mv $i ${i%.fits}.fit
done

# Generate the lorri info files
# Compile program for generating lorri infofiles
cd $DIR/sbmt/misc/programs/lorri_pds/
cp $DIR/nh_spice.mk .
./compile.sh
./run-pluto.sh


# Copy over any new MVIC fits data
mkdir -p /project/nearsdc/data/NEWHORIZONS/MVIC/images2
find /project/lorri/data/soc/pluto/level2/mvi/current -name "*fit" | xargs cp -R -u -L -t /project/nearsdc/data/NEWHORIZONS/MVIC/images2
# Remove and do not process bad images
rm -f /project/nearsdc/data/NEWHORIZONS/MVIC/images2/m*0287692291*.fit
rm -f /project/nearsdc/data/NEWHORIZONS/MVIC/images2/m*0287694091*.fit
rm -f /project/nearsdc/data/NEWHORIZONS/MVIC/images2/m*0293790651*.fit
rm -f /project/nearsdc/data/NEWHORIZONS/MVIC/images2/mp*.fit

# Compile program for generating mvic infofiles
cd $DIR/sbmt/misc/programs/mvic_pds/
cp $DIR/nh_spice.mk .
./compile.sh
./run-pluto.sh


# Copy over any new LEISA fits data
mkdir -p /project/nearsdc/data/NEWHORIZONS/LEISA/images2
find /project/lorri/data/soc/pluto/level2/lei/current -name "*fit" | xargs cp -R -u -L -t /project/nearsdc/data/NEWHORIZONS/LEISA/images2
# Remove and do not process bad images
rm -f /project/nearsdc/data/NEWHORIZONS/LEISA/images2/lsb_028769*.fit

# Compile program for generating leisa infofiles
cd $DIR/sbmt/misc/programs/leisa_pds/
cp $DIR/nh_spice.mk .
./compile.sh
./run-pluto.sh