package edu.jhuapl.saavtk.model;

public enum ModelNames
{
    TORSO,
    SCENARIO_COLLECTION,
    SMALL_BODY,
    LINE_STRUCTURES,
    POLYGON_STRUCTURES,
    CIRCLE_STRUCTURES,
    ELLIPSE_STRUCTURES,
    POINT_STRUCTURES,
    CIRCLE_SELECTION,
    IMAGES,
    GRATICULE,
    GRAVITY_VECTOR_FIELD,
    COLOR_IMAGES,
    CUBE_IMAGES,
    PERSPECTIVE_IMAGE_BOUNDARIES,
    LINEAMENT,
    SPECTRA,
    LIDAR_SUMMARY,
    LIDAR_BROWSE,
    LIDAR_SEARCH,
    LIDAR_HYPERTREE_SEARCH,
    DEM_BOUNDARY,
    TRACKS,
    DEM,
    STATISTICS
}
