#!/bin/sh

# *** EXPORT CONTROLLED (12/2013) ***

# Program to convert a mapmaker cube into a standard format such as OBJ
# Copy this file into the SBMT release (into the same folder as the runsbmt file).

DIR=`dirname "$0"`
export DYLD_LIBRARY_PATH="$DIR/lib/mac64:$DYLD_LIBRARY_PATH"
/usr/libexec/java_home -v 1.6 -a x86_64 -exec java "-Djava.library.path=$DIR/lib/mac64" -cp "$DIR/lib/near.jar" edu.jhuapl.near.server.ConvertMaplet $@
