include ${SBMTROOT}/config/Makefiles/Variables
#
# Specify the list of scripts to install and the destination
# if the destination is not the default specified by BINROOT
#
SCRIPTFILES         := deploy-sbmt-extras.sh
SPECIAL_DESTINATION :=

# Include the common processing for this this Makefile.
include ${SBMTROOT}/config/Makefiles/Master
