# Specify the list of scripts to install in $BINROOT. To install
# in a different location, specify the location in the 
# $SPECIAL_DESTINATION variable below.
#
SCRIPTFILES :=  

SPECIAL_DESTINATION :=


#
#
# Include the common processing for this this Makefile.
include ${SBMTROOT}/config/Makefiles/Master
