# Specify the list of scripts to install and the destination
# if the destination is not the default specified by BINROOT
#
SCRIPTFILES         := make_gallery_webpage.py jquery.js main.js
SPECIAL_DESTINATION :=

# Include the common processing for this this Makefile.
include ${SBMTROOT}/config/Makefiles/Master
