#
# Specify the list of subdirectories separated by spaces.
#
SUBDIRS := make_gallery_webpage fits2thumbnails fc_pds

# Include the common processing for this this Makefile.
include ${SBMTROOT}/config/Makefiles/Master

