#!/bin/bash

# Usage: ./runmapmaker pathToMapmakerExecutable name metersPerPixel lat lon 

MAPMAKER=$1
NAME=$2
METERS_PER_PIXEL=$3
LAT=$4
LON=$5

EXECDIR=`dirname $MAPMAKER`
DIR=`dirname $EXECDIR`
cd $DIR

export LD_LIBRARY_PATH=$EXECDIR:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=$EXECDIR:$DYLD_LIBRARY_PATH

echo -e "$NAME\n512 $METERS_PER_PIXEL\nL\n$LAT,$LON\nn\nn\nn\nn\nn\nn\n" | $MAPMAKER
